import type { Metadata } from 'next'
import { CopyButton } from './CopyButton'

export const metadata: Metadata = {
  title: 'Figma Make Setup',
  description: 'How to set up a client-branded prototype in Figma Make using the AI Chat UI component library.',
}

const STEP1_PROMPT = `Clone the following GitHub repository into this Figma Make project:
https://github.com/lizzie-teo/conjure-ui.git

Import ONLY these paths — do not clone the full repo:
- components/         (component source files — skip any *.stories.tsx files)
- app/theme.css       (design tokens and per-client theme classes)
- app/globals.css     (Tailwind CSS wiring — do not edit this file)
- lib/tokens.css      (token reference — read-only, comments only)

Important notes for rendering:
1. This library uses the \`motion\` package (Framer Motion v12) for animations.
   Do not remove or replace motion imports — components will break without them.
2. The Button component and all design tokens follow shadcn/ui semantic naming
   (--primary, --secondary, --muted, --accent, --destructive, --border, --ring, etc.).
3. All colours and spacing are CSS custom properties — never hardcoded.
   Do not add hex values or Tailwind colour utilities directly.

After cloning, render the demo entry point so components are visible on the canvas.
The app shell is in the \`demo/\` folder if you need a starting render target.`

const STEP3_PROMPT = `I have a white-label React component library that uses shadcn/ui's semantic CSS variable
naming convention. I need to map a client's brand colours to the correct semantic token names.

The library's semantic variables are:
  --background         (page/app background)
  --foreground         (primary text on background)
  --card               (card surface)
  --card-foreground    (text on card)
  --primary            (main brand colour — buttons, links, active states)
  --primary-foreground (text on primary colour)
  --secondary          (secondary actions, subtle highlights)
  --secondary-foreground
  --muted              (disabled states, placeholders, subtle backgrounds)
  --muted-foreground   (secondary/subdued text)
  --accent             (hover states, selected items)
  --accent-foreground
  --destructive        (errors, warnings, delete actions)
  --destructive-foreground
  --border             (dividers, input borders)
  --input              (input field background)
  --ring               (focus ring colour)
  --radius             (border-radius for cards and buttons, e.g. 0.5rem)

The client's brand colours are:
[CLIENT COLOURS — paste what you collected from their website here]

Please output a single CSS class block using this exact format:

.theme-[clientname] {
  --background: ;
  --foreground: ;
  --card: ;
  --card-foreground: ;
  --primary: ;
  --primary-foreground: ;
  --secondary: ;
  --secondary-foreground: ;
  --muted: ;
  --muted-foreground: ;
  --accent: ;
  --accent-foreground: ;
  --destructive: ;
  --destructive-foreground: ;
  --border: ;
  --input: ;
  --ring: ;
  --radius: ;
}

Use oklch() colour format where possible for perceptual consistency.
If a semantic value cannot be inferred from the client colours, derive a sensible
default that respects their palette (e.g. lighten the primary by 80% for --muted).
Replace [clientname] with a lowercase kebab-case version of the client's name.`

const STEP4_PROMPT = `I have a new client theme CSS block to add to this project.

1. Open app/theme.css and append the following class at the end of the file,
   after all existing .theme-* classes. Do not modify the :root block or any
   existing theme classes — only add the new one:

[PASTE CSS BLOCK HERE]

2. Find the root wrapper element in the demo app (likely in demo/App.tsx or
   demo/index.tsx) and add the class name that matches the new .theme-* class
   you just added (e.g. className="theme-clientname") to the outermost div.

3. Reload the canvas so the components re-render with the new theme.

The components use CSS custom properties throughout — once the class is applied
at the root, every component should automatically pick up the client's colours
without any component-level edits.`

const STEPS = [
  {
    number: '01',
    title: 'Clone the Library into Figma Make',
    intro: 'Open a new Figma Make project and paste the prompt below into the Figma Make chat. Wait for it to finish cloning and rendering — you should see the base components in the default "clean look" theme.',
    prompt: STEP1_PROMPT,
    label: 'Figma Make chat prompt',
  },
  {
    number: '02',
    title: 'Extract the Client\'s Brand Colours',
    intro: null,
    prompt: null,
    label: null,
  },
  {
    number: '03',
    title: 'Map Client Colours to Semantic Tokens',
    intro: 'The library expects shadcn/ui\'s semantic naming, not generic names like brand-blue. Open Claude, GitHub Copilot Chat, or any AI assistant. Paste this prompt, then replace the [CLIENT COLOURS] section with what you collected in Step 2.',
    prompt: STEP3_PROMPT,
    label: 'AI assistant prompt',
  },
  {
    number: '04',
    title: 'Apply the Client Theme in Figma Make',
    intro: 'Go back to Figma Make. Copy the .theme-[clientname] { … } block returned by the AI, then paste this prompt — replacing [PASTE CSS BLOCK HERE] with the full CSS block from Step 3.',
    prompt: STEP4_PROMPT,
    label: 'Figma Make chat prompt',
  },
]

const TOKENS = [
  { token: '--primary', controls: 'Buttons, active state, links' },
  { token: '--background', controls: 'App background' },
  { token: '--card', controls: 'Message bubbles, cards, panels' },
  { token: '--muted', controls: 'Placeholder text, disabled states' },
  { token: '--border', controls: 'Input borders, dividers' },
  { token: '--radius', controls: 'Corner rounding on all components' },
  { token: '--destructive', controls: 'Error states, delete confirmations' },
  { token: '--ring', controls: 'Keyboard focus outline' },
]

const TROUBLESHOOTING: { issue: string; fix: string; prompt?: string; promptLabel?: string }[] = [
  {
    issue: 'Components look unstyled / all white',
    fix: 'The globals.css @theme inline mappings may not have loaded. Make sure Figma Make imported app/globals.css and that it has not been edited or removed.',
  },
  {
    issue: 'Colours are not changing after applying the theme class',
    fix: 'Check that the class name on the root div exactly matches the CSS class name — e.g. theme-acme must match .theme-acme { }. Class names are case-sensitive.',
  },
  {
    issue: 'Animations are missing or broken',
    fix: 'The motion package must be present. Ask Figma Make to check that motion is listed in the project\'s dependencies and that no motion imports were removed during cloning.',
  },
  {
    issue: 'A token is missing from the mapped CSS',
    fix: 'Go back to Step 3 and ask the AI agent to fill in the missing token, specifying what kind of colour it should be — e.g. "derive --ring as a semi-transparent version of --primary".',
  },
]

function PromptBlock({ prompt, label }: { prompt: string; label: string }) {
  return (
    <div className="mt-6 rounded-xl overflow-hidden border border-border shadow-card">
      <div className="flex items-center justify-between px-4 py-2.5 border-b border-border bg-muted/60">
        <span className="text-xs font-medium text-muted-foreground tracking-wide uppercase">{label}</span>
        <CopyButton text={prompt} />
      </div>
      <pre className="p-5 md:p-6 text-sm leading-relaxed overflow-x-auto bg-foreground text-background font-mono whitespace-pre-wrap break-words">
        {prompt}
      </pre>
    </div>
  )
}

function Step2Content() {
  return (
    <div className="mt-6 space-y-4">
      <p className="text-muted-foreground leading-relaxed">
        Before the AI can remap colours, you need to collect the client&apos;s brand CSS. Two ways to do this:
      </p>
      <div className="grid gap-4 md:grid-cols-2">
        <div className="rounded-xl border border-border bg-card p-5 md:p-6 shadow-sm">
          <div className="flex items-center gap-2.5 mb-3">
            <span className="flex size-6 items-center justify-center rounded-full bg-primary text-primary-foreground text-xs font-semibold">A</span>
            <h4 className="text-sm font-semibold">Browser DevTools (recommended)</h4>
          </div>
          <ol className="space-y-2 text-sm text-muted-foreground leading-relaxed list-none">
            <li className="flex gap-2"><span className="text-foreground font-medium shrink-0">1.</span>Open the client&apos;s live website in Chrome or Safari.</li>
            <li className="flex gap-2"><span className="text-foreground font-medium shrink-0">2.</span>Open DevTools → Elements tab.</li>
            <li className="flex gap-2"><span className="text-foreground font-medium shrink-0">3.</span>Click the <code className="bg-muted px-1 py-0.5 rounded text-xs font-mono">&lt;html&gt;</code> or <code className="bg-muted px-1 py-0.5 rounded text-xs font-mono">&lt;body&gt;</code> element and look at the Computed styles panel for any <code className="bg-muted px-1 py-0.5 rounded text-xs font-mono">--</code> CSS custom properties. Copy everything you find.</li>
            <li className="flex gap-2"><span className="text-foreground font-medium shrink-0">4.</span>Also note: primary brand colour, background, text colour, button colours, border colours, and corner radius.</li>
          </ol>
        </div>
        <div className="rounded-xl border border-border bg-card p-5 md:p-6 shadow-sm">
          <div className="flex items-center gap-2.5 mb-3">
            <span className="flex size-6 items-center justify-center rounded-full bg-secondary text-secondary-foreground border border-border text-xs font-semibold">B</span>
            <h4 className="text-sm font-semibold">Copy the stylesheet</h4>
          </div>
          <ol className="space-y-2 text-sm text-muted-foreground leading-relaxed list-none">
            <li className="flex gap-2"><span className="text-foreground font-medium shrink-0">1.</span>In DevTools → Network tab, filter by &quot;CSS&quot;.</li>
            <li className="flex gap-2"><span className="text-foreground font-medium shrink-0">2.</span>Find the main stylesheet, open it, and search for <code className="bg-muted px-1 py-0.5 rounded text-xs font-mono">:root &#123;</code> or <code className="bg-muted px-1 py-0.5 rounded text-xs font-mono">--color</code> to find their token definitions.</li>
            <li className="flex gap-2"><span className="text-foreground font-medium shrink-0">3.</span>Copy the relevant section.</li>
          </ol>
        </div>
      </div>
    </div>
  )
}

export default function FigmaMakePage() {
  return (
    <div className="min-h-screen bg-background text-foreground">

      {/* Page header */}
      <div className="border-b border-border bg-card">
        <div className="mx-auto max-w-3xl px-6 md:px-8 py-12 md:py-16">
          <p className="text-xs font-semibold tracking-widest uppercase text-muted-foreground mb-3">
            Designer Guide
          </p>
          <h1 className="text-3xl md:text-4xl font-semibold tracking-tight text-foreground mb-4">
            White-Label Theming<br className="hidden md:block" /> in Figma Make
          </h1>
          <p className="text-base md:text-lg text-muted-foreground leading-relaxed max-w-xl">
            Clone the component library into Figma Make, extract a client&apos;s brand colours, and have an AI remap the CSS tokens — without touching any component files.
          </p>
        </div>
      </div>

      <div className="mx-auto max-w-3xl px-6 md:px-8 py-12 md:py-16 space-y-16">

        {/* Before You Start */}
        <section>
          <h2 className="text-lg font-semibold mb-5">Before You Start</h2>
          <div className="grid gap-4 md:grid-cols-3">
            <div className="rounded-xl border border-border bg-card p-5 shadow-sm">
              <h3 className="text-sm font-semibold mb-2">What this library is</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                A white-label AI chat UI kit built in React + Tailwind CSS. Every colour, radius, and shadow is driven by a CSS variable — no component editing needed.
              </p>
            </div>
            <div className="rounded-xl border border-border bg-card p-5 shadow-sm">
              <h3 className="text-sm font-semibold mb-2">Key dependencies</h3>
              <ul className="text-sm text-muted-foreground space-y-1.5">
                <li><code className="bg-muted px-1 py-0.5 rounded text-xs font-mono">motion</code> — built-in animations. Do not remove imports.</li>
                <li><code className="bg-muted px-1 py-0.5 rounded text-xs font-mono">shadcn/ui</code> — semantic token naming (<code className="bg-muted px-1 py-0.5 rounded text-xs font-mono">--primary</code>, <code className="bg-muted px-1 py-0.5 rounded text-xs font-mono">--muted</code>, etc.)</li>
                <li><code className="bg-muted px-1 py-0.5 rounded text-xs font-mono">Tailwind v4</code> — utilities generated from CSS variables.</li>
              </ul>
            </div>
            <div className="rounded-xl border border-border bg-card p-5 shadow-sm">
              <h3 className="text-sm font-semibold mb-2">License</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                MIT License © 2026 Lizzie Teo. Free to use, copy, modify, and distribute in client work. Keep the MIT notice in any distributed build.
              </p>
            </div>
          </div>
        </section>

        {/* Steps */}
        {STEPS.map((step, i) => (
          <section key={step.number} className="relative">
            <div className="flex items-start gap-4 md:gap-6">
              <div className="flex flex-col items-center shrink-0">
                <div className="flex size-10 md:size-12 items-center justify-center rounded-full bg-primary text-primary-foreground text-sm md:text-base font-semibold">
                  {i + 1}
                </div>
                {i < STEPS.length - 1 && (
                  <div className="mt-4 w-px flex-1 bg-border" style={{ minHeight: '2rem' }} />
                )}
              </div>
              <div className="flex-1 pb-2">
                <div className="flex items-center gap-3 mb-1">
                  <span className="text-xs font-semibold tracking-widest uppercase text-muted-foreground">
                    Step {step.number}
                  </span>
                </div>
                <h2 className="text-xl md:text-2xl font-semibold tracking-tight mb-3">
                  {step.title}
                </h2>
                {step.intro && (
                  <p className="text-muted-foreground leading-relaxed">
                    {step.intro}
                  </p>
                )}
                {step.prompt && step.label ? (
                  <PromptBlock prompt={step.prompt} label={step.label} />
                ) : (
                  <Step2Content />
                )}
              </div>
            </div>
          </section>
        ))}

        {/* Divider */}
        <hr className="border-border" />

        {/* Troubleshooting */}
        <section>
          <h2 className="text-lg font-semibold mb-5">Troubleshooting</h2>
          <div className="space-y-3">
            {TROUBLESHOOTING.map((item) => (
              <div key={item.issue} className="rounded-xl border border-border bg-card p-5 md:p-6 shadow-sm">
                <h3 className="text-sm font-semibold mb-1.5">{item.issue}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{item.fix}</p>
                {item.prompt && item.promptLabel && (
                  <PromptBlock prompt={item.prompt} label={item.promptLabel} />
                )}
              </div>
            ))}
          </div>
        </section>

        {/* Quick Reference */}
        <section>
          <h2 className="text-lg font-semibold mb-5">Token Quick Reference</h2>
          <div className="rounded-xl border border-border overflow-hidden shadow-sm">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border bg-muted/60">
                  <th className="text-left px-5 py-3 font-semibold text-xs tracking-wide uppercase text-muted-foreground w-[40%]">Token</th>
                  <th className="text-left px-5 py-3 font-semibold text-xs tracking-wide uppercase text-muted-foreground">What it controls</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {TOKENS.map((row, i) => (
                  <tr key={row.token} className={i % 2 === 0 ? 'bg-card' : 'bg-muted/20'}>
                    <td className="px-5 py-3.5">
                      <code className="text-xs font-mono bg-muted px-1.5 py-0.5 rounded text-foreground">{row.token}</code>
                    </td>
                    <td className="px-5 py-3.5 text-muted-foreground">{row.controls}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

      </div>
    </div>
  )
}
